sudo: false
language: swift
osx_image: xcode9.4

jobs:
  include:
    - name: "Building AccessibleCore and AccessibleTool"
      stage: compile
      script: swift build
    - name: "Testing AccessibleCore"
      stage: test
      script: swift test
